server:
  port: 5001
  servlet:
    context-path: /api/

spring:
  application:
    name: spring-boot-file-upload

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
