server:
  port: 5001
  servlet:
    context-path: /api/

spring:
  application:
    name: spring-boot-3-security
    security:
      jwt:
        secret-key: 3273357638792F423F4528482B4B6250655368566D597133743677397A244326
        expiration: 60000 # 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        default_schema: iam
        format_sql: true
    show-sql: false

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
#        token:
#          expire-length: 3600000
