server:
  port: 5001
  servlet:
    context-path: /api/

spring:
  application:
    name: spring-boot-3-security

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        default_schema: iam
        format_sql: true
    show-sql: false

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
#        token:
#          expire-length: 3600000
