server:
  port: 8082

spring:
  application:
    name: spring-rest
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/dev?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExist=true&Timezone=UTC
    username: root
    password: Password123