spring:
  application:
    name: discovery-service

# default port for eureka server
server:
  port: 8761

# eureka by default will register itself as a client. So, we need to set it to false.
# What's a client server? See other microservices (student, auth, etc).
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

security:
  basic:
    enabled: false
