#rabbit mq settings
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: changeMe

  application:
    name: amqp-publisher
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/publisher?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: Password123
