package com.wiltech.insurly.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI metadata. The spec is generated by springdoc from the {@code *RestService}
 * controllers and served at {@code /api/v3/api-docs}; Swagger UI is at
 * {@code /api/swagger-ui.html}. Both are disabled by default in the {@code prod}
 * profile (see application-prod.yaml).
 */
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI insurlyOpenApi() {
        return new OpenAPI().info(new Info()
                .title("insurly API")
                .version("v1")
                .description("""
                        Car-insurance quotes.

                        - Public: guest quotes (POST /api/quotes/car) and retrieval by id + guestToken.
                        - Users (/api/users/{userId}/**): a user's own or (as admin, on their behalf) another
                          user's profile, cars, addresses, phones, licences and quotes. userId is "me" or a user id.
                        - Admin (/api/admin/**): the customer list, per-user profile + roles, providers, and the
                          dashboard. Requires the ADMIN role.

                        Responses use a HAL-ish envelope: the resource sits under `_data.<root>` with
                        sidecar `_metadata` / `_metaLinks` / `_messages`.""")
                .contact(new Contact().name("insurly")));
    }
}
