
# Prevent DDos by IP, restrict up to 5 calls per second
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 100
              unit: seconds

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
