version: '3.2'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3307:3306
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: Password123
            MYSQL_DATABASE: dev
        volumes:
            - microservices_dev:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 9090:8080

volumes:
    microservices_dev:
