[project]
name = "resource-management-api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "pyjwt[crypto]",
    "httpx",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.52.4",
    "aiosqlite>=0.22.1",
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk",
]
