version: '3.2'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 2012:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: spring_app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: test123
    volumes:
      - microservices_dev:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

volumes:
  microservices_dev:
